import type {
  AfterSalahEntry,
  DailyJourneyConfig,
  FeaturedEntry,
  Milestone,
  SpiritualContent,
  TheoCategory,
  TheoCollection,
  TheoData,
  TheoReference,
  TheoSettings,
  TheoSubcategory,
  TheoTag,
} from "./types"

let n = 0
const id = (p: string) => `${p}_${(++n).toString().padStart(4, "0")}`

function c(p: Partial<SpiritualContent> & Pick<SpiritualContent, "kind" | "title">): SpiritualContent {
  return {
    id: id(p.kind),
    arabic: "",
    transliteration: "",
    translation: "",
    benefit: "",
    notes: "",
    repetition: "none",
    category: "",
    subcategory: "",
    occasion: "",
    tags: [],
    quranReference: "",
    hadithReference: "",
    source: "",
    displayOrder: n,
    verification: "unverified",
    status: "draft",
    routines: [],
    isQuranic: false,
    surahName: "",
    surahNumber: null,
    ayahRange: "",
    rabbanaNumber: null,
    featured: false,
    collections: [],
    createdAt: new Date(Date.now() - n * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - n * 3600000).toISOString(),
    ...p,
  }
}

export function buildTheoSeed(): TheoData {
  n = 0
  const categories: TheoCategory[] = [
    { id: "cat_after_salah", name: "After Salah", description: "Adhkars to be recited after each prayer.", icon: "Sun", slug: "after-salah", parent: null, displayOrder: 1, visibility: true, status: "published" },
    { id: "cat_morning", name: "Morning Adhkar", description: "Morning remembrance routines.", icon: "Sunrise", slug: "morning-adhkar", parent: null, displayOrder: 2, visibility: true, status: "published" },
    { id: "cat_evening", name: "Evening Adhkar", description: "Evening remembrance routines.", icon: "Sunset", slug: "evening-adhkar", parent: null, displayOrder: 3, visibility: true, status: "published" },
    { id: "cat_sleep", name: "Before Sleep", description: "Remembrance before sleeping.", icon: "Moon", slug: "before-sleep", parent: null, displayOrder: 4, visibility: true, status: "published" },
    { id: "cat_daily", name: "Daily Duas", description: "General daily supplications.", icon: "Heart", slug: "daily-duas", parent: null, displayOrder: 5, visibility: true, status: "published" },
    { id: "cat_rabbana", name: "40 Rabbana", description: "The 40 Rabbana supplications from the Qur'an.", icon: "BookOpen", slug: "40-rabbana", parent: null, displayOrder: 6, visibility: true, status: "published" },
    { id: "cat_ruqiyah", name: "Ruqiyah", description: "Verified Ruqiyah verses and supplications.", icon: "Shield", slug: "ruqiyah", parent: null, displayOrder: 7, visibility: true, status: "published" },
    { id: "cat_missed", name: "Missed Raka'ah", description: "Compensatory prayer guidance.", icon: "Repeat", slug: "missed-rakaah", parent: null, displayOrder: 8, visibility: true, status: "published" },
    { id: "cat_hajj", name: "Hajj & Umrah", description: "Pilgrimage supplications.", icon: "MapPin", slug: "hajj-umrah", parent: null, displayOrder: 9, visibility: true, status: "published" },
    { id: "cat_tasbeeh", name: "Tasbeeh", description: "Dhikr and glorification.", icon: "Sparkles", slug: "tasbeeh", parent: null, displayOrder: 10, visibility: true, status: "published" },
    { id: "cat_qrem", name: "Quranic Reminder", description: "Qur'anic supplications and reminders.", icon: "BookText", slug: "quranic-reminder", parent: null, displayOrder: 11, visibility: true, status: "published" },
    { id: "cat_protection", name: "Protection", description: "Seeking protection from harm.", icon: "ShieldCheck", slug: "protection", parent: null, displayOrder: 12, visibility: true, status: "published" },
    { id: "cat_forgiveness", name: "Forgiveness", description: "Seeking forgiveness.", icon: "HeartHandshake", slug: "forgiveness", parent: null, displayOrder: 13, visibility: true, status: "published" },
    { id: "cat_travel", name: "Travel", description: "Travel supplications.", icon: "Plane", slug: "travel", parent: null, displayOrder: 14, visibility: true, status: "published" },
    { id: "cat_healing", name: "Healing", description: "Supplications for healing.", icon: "Stethoscope", slug: "healing", parent: null, displayOrder: 15, visibility: true, status: "published" },
    { id: "cat_knowledge", name: "Knowledge", description: "Seeking beneficial knowledge.", icon: "GraduationCap", slug: "knowledge", parent: null, displayOrder: 16, visibility: true, status: "published" },
    { id: "cat_rizq", name: "Rizq", description: "Supplications for provision.", icon: "Coins", slug: "rizq", parent: null, displayOrder: 17, visibility: true, status: "published" },
    { id: "cat_family", name: "Family", description: "Family and relationships.", icon: "Users", slug: "family", parent: null, displayOrder: 18, visibility: true, status: "published" },
    { id: "cat_gratitude", name: "Gratitude", description: "Gratitude and thankfulness.", icon: "HandHeart", slug: "gratitude", parent: null, displayOrder: 19, visibility: true, status: "published" },
    { id: "cat_guidance", name: "Guidance", description: "Seeking guidance.", icon: "Compass", slug: "guidance", parent: null, displayOrder: 20, visibility: true, status: "published" },
  ]

  const subcategories: TheoSubcategory[] = [
    { id: "sub_prot_m", name: "Morning Protection", parent: "cat_protection", slug: "morning-protection", displayOrder: 1, hidden: false, archived: false },
    { id: "sub_prot_e", name: "Evening Protection", parent: "cat_protection", slug: "evening-protection", displayOrder: 2, hidden: false, archived: false },
    { id: "sub_prot_s", name: "Sleep Protection", parent: "cat_protection", slug: "sleep-protection", displayOrder: 3, hidden: false, archived: false },
    { id: "sub_prot_f", name: "Family Protection", parent: "cat_protection", slug: "family-protection", displayOrder: 4, hidden: false, archived: false },
  ]

  const content: SpiritualContent[] = [
    c({
      kind: "dua",
      title: "Increase in Knowledge",
      arabic: "رَبِّ زِدْنِي عِلْمًا",
      transliteration: "Rabbi zidni ilma",
      translation: "My Lord, increase me in knowledge.",
      benefit: "A supplication for beneficial knowledge, recited by Musa (AS) and encouraged for all seekers.",
      notes: "From Surah Taha 20:114.",
      repetition: "none",
      category: "cat_knowledge",
      tags: ["knowledge", "gratitude"],
      quranReference: "20:114",
      source: "Qur'an",
      verification: "verified",
      status: "published",
      routines: ["daily"],
      isQuranic: true,
      surahName: "Taha",
      surahNumber: 20,
      ayahRange: "114",
      featured: true,
    }),
    c({
      kind: "dua",
      title: "Ease and Relief",
      arabic: "اللَّهُمَّ لَا سَهْلَ إلَّا مَا جَعَلْتَهُ سَهْلًا",
      transliteration: "Allahumma la sahla illa ma ja'altahu sahla",
      translation: "O Allah, there is no ease except what You make easy.",
      benefit: "Recited for relief from difficulty.",
      notes: "Weak but well-known invocation; verify chain before public promotion.",
      repetition: "3",
      category: "cat_daily",
      tags: ["guidance", "healing"],
      source: "Sunan Ibn Majah",
      verification: "under_review",
      status: "published",
      routines: ["morning", "evening"],
    }),
    c({
      kind: "adkar",
      title: "Morning Remembrance",
      arabic: "أَصْبَحْنَا وَأَصْبَحَ الْمُلْكُ لِلَّهِ",
      transliteration: "Asbahna wa asbahal mulku lillah",
      translation: "We have reached the morning and the dominion belongs to Allah.",
      benefit: "Morning dhikr affirming Allah's sovereignty.",
      notes: "",
      repetition: "1",
      category: "cat_morning",
      tags: ["morning"],
      source: "Muslim",
      verification: "verified",
      status: "published",
      routines: ["morning", "upon_waking"],
    }),
    c({
      kind: "adkar",
      title: "Evening Remembrance",
      arabic: "أَمْسَيْنَا وَأَمْسَى الْمُلْكُ لِلَّهِ",
      transliteration: "Amsayna wa amsal mulku lillah",
      translation: "We have reached the evening and the dominion belongs to Allah.",
      benefit: "Evening dhikr affirming Allah's sovereignty.",
      notes: "",
      repetition: "1",
      category: "cat_evening",
      tags: ["evening"],
      source: "Muslim",
      verification: "verified",
      status: "published",
      routines: ["evening"],
    }),
    c({
      kind: "adkar",
      title: "Before Sleep",
      arabic: "بِاسْمِكَ اللَّهُمَّ أَمُوتُ وَأَحْيَا",
      transliteration: "Bismika Allahumma amutu wa ahya",
      translation: "In Your name, O Allah, I die and I live.",
      benefit: "Recited before sleeping.",
      notes: "",
      repetition: "1",
      category: "cat_sleep",
      tags: ["sleep"],
      source: "Bukhari",
      verification: "verified",
      status: "published",
      routines: ["before_sleep"],
    }),
    c({
      kind: "quranic",
      title: "The Throne Verse Reminder",
      arabic: "اللَّهُ لَا إِلَٰهَ إِلَّا هُوَ الْحَيُّ الْقَيُّومُ",
      transliteration: "Allahu la ilaha illa huwal hayyul qayyoom",
      translation: "Allah - there is no deity except Him, the Ever-Living, the Sustainer.",
      benefit: "Ayat al-Kursi; profound protection and greatness of Allah.",
      notes: "Qur'anic verse, not ordinary dua.",
      repetition: "1",
      category: "cat_qrem",
      tags: ["protection", "quranic reminder"],
      quranReference: "2:255",
      source: "Qur'an",
      verification: "verified",
      status: "published",
      routines: ["evening"],
      isQuranic: true,
      surahName: "Al-Baqarah",
      surahNumber: 2,
      ayahRange: "255",
      featured: true,
    }),
    c({
      kind: "rabbana",
      title: "Our Lord, grant us good",
      arabic: "رَبَّنَا آتِنَا فِي الدُّنْيَا حَسَنَةً وَفِي الْآخِرَةِ حَسَنَةً وَقِنَا عَذَابَ النَّارِ",
      transliteration: "Rabbana atina fid-dunya hasanah wa fil-akhirati hasanah wa qina adhaban-nar",
      translation: "Our Lord, give us good in this world and good in the Hereafter, and protect us from the punishment of the Fire.",
      benefit: "Comprehensive supplication for this world and the next.",
      notes: "1 of 40 Rabbana.",
      repetition: "none",
      category: "cat_rabbana",
      tags: ["forgiveness", "guidance"],
      quranReference: "2:201",
      source: "Qur'an",
      verification: "verified",
      status: "published",
      routines: [],
      isQuranic: true,
      surahName: "Al-Baqarah",
      surahNumber: 2,
      ayahRange: "201",
      rabbanaNumber: 1,
      featured: true,
    }),
    c({
      kind: "rabbana",
      title: "Our Lord, accept from us",
      arabic: "رَبَّنَا تَقَبَّلْ مِنَّا إِنَّكَ أَنْتَ السَّمِيعُ الْعَلِيمُ",
      transliteration: "Rabbana taqabbal minna innaka antas-sami'ul 'alim",
      translation: "Our Lord, accept from us; indeed You are the Hearing, the Knowing.",
      benefit: "Supplication for acceptance of deeds.",
      notes: "2 of 40 Rabbana.",
      repetition: "none",
      category: "cat_rabbana",
      tags: ["guidance"],
      quranReference: "2:127",
      source: "Qur'an",
      verification: "verified",
      status: "published",
      routines: [],
      isQuranic: true,
      surahName: "Al-Baqarah",
      surahNumber: 2,
      ayahRange: "127",
      rabbanaNumber: 2,
    }),
    c({
      kind: "ruqiyah",
      title: "Surah Al-Fatihah",
      arabic: "بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ ﴿ الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ ﴾",
      transliteration: "Bismillahir rahmanir rahim. Alhamdu lillahi rabbil 'alamin",
      translation: "In the name of Allah, the Entirely Merciful. All praise is due to Allah, Lord of the worlds.",
      benefit: "Recited in Ruqiyah as healing and protection.",
      notes: "Qur'anic; verified Ruqiyah content.",
      repetition: "3",
      category: "cat_ruqiyah",
      tags: ["healing", "protection"],
      quranReference: "1:1-7",
      source: "Qur'an",
      verification: "verified",
      status: "published",
      routines: [],
      isQuranic: true,
      surahName: "Al-Fatihah",
      surahNumber: 1,
      ayahRange: "1-7",
    }),
    c({
      kind: "dua",
      title: "Draft Forgiveness Dua",
      arabic: "",
      transliteration: "",
      translation: "O Allah, forgive me and my parents.",
      benefit: "",
      notes: "Needs Arabic and verification before publishing.",
      repetition: "none",
      category: "cat_forgiveness",
      tags: ["forgiveness"],
      verification: "unverified",
      status: "draft",
      routines: [],
    }),
  ]

  const collections: TheoCollection[] = [
    { id: "col_morning", name: "Morning Adhkar", description: "Start the day with remembrance.", icon: "Sunrise", cover: "", items: [{ contentId: content[2].id, order: 1, required: true, repetition: "1" }], status: "published" },
    { id: "col_evening", name: "Evening Adhkar", description: "End the day with remembrance.", icon: "Sunset", cover: "", items: [{ contentId: content[3].id, order: 1, required: true, repetition: "1" }], status: "published" },
    { id: "col_salah", name: "After Salah", description: "Post-prayer adhkars.", icon: "Sun", cover: "", items: [{ contentId: content[1].id, order: 1, required: false, repetition: "3" }], status: "published" },
    { id: "col_sleep", name: "Before Sleep", description: "Remembrance before sleep.", icon: "Moon", cover: "", items: [{ contentId: content[4].id, order: 1, required: true, repetition: "1" }], status: "published" },
    { id: "col_doxology", name: "Daily Doxology", description: "The complete daily journey.", icon: "Heart", cover: "", items: [], status: "published" },
    { id: "col_rabbana", name: "40 Rabbana", description: "The 40 Rabbana supplications.", icon: "BookOpen", cover: "", items: [{ contentId: content[6].id, order: 1, required: false, repetition: "none" }, { contentId: content[7].id, order: 2, required: false, repetition: "none" }], status: "published" },
    { id: "col_ruqiyah", name: "Ruqiyah", description: "Verified Ruqiyah collection.", icon: "Shield", cover: "", items: [{ contentId: content[8].id, order: 1, required: false, repetition: "3" }], status: "published" },
  ]

  const references: TheoReference[] = [
    { id: "ref_1", type: "quran", surah: "Al-Baqarah", ayah: "255", hadithCollection: "", hadithNumber: "", sourceBook: "Qur'an", referenceText: "Ayat al-Kursi — protection and greatness of Allah.", authenticity: "Mutawatir", notes: "Always cite chapter and verse." },
    { id: "ref_2", type: "hadith", surah: "", ayah: "", hadithCollection: "Sahih Muslim", hadithNumber: "2723", sourceBook: "Sahih Muslim", referenceText: "Morning and evening remembrance of Allah's dominion.", authenticity: "Sahih", notes: "" },
  ]

  const tags: TheoTag[] = [
    "Morning", "Evening", "Sleep", "Prayer", "Protection", "Forgiveness", "Travel", "Healing",
    "Rizq", "Knowledge", "Family", "Anxiety", "Gratitude", "Guidance",
  ].map((t, i) => ({ id: `tag_${(i + 1).toString().padStart(3, "0")}`, name: t, slug: t.toLowerCase() }))

  const journey: DailyJourneyConfig = {
    sections: [
      { key: "morning", label: "Morning Adhkar", required: true, collectionId: "col_morning" },
      { key: "after_fajr", label: "After Fajr", required: true, collectionId: "col_salah" },
      { key: "after_dhuhr", label: "After Dhuhr", required: true, collectionId: "col_salah" },
      { key: "after_asr", label: "After Asr", required: true, collectionId: "col_salah" },
      { key: "after_maghrib", label: "After Maghrib", required: true, collectionId: "col_salah" },
      { key: "evening", label: "Evening Adhkar", required: true, collectionId: "col_evening" },
      { key: "after_isha", label: "After Isha", required: true, collectionId: "col_salah" },
      { key: "before_sleep", label: "Before Sleep", required: true, collectionId: "col_sleep" },
    ],
  }

  const afterSalah: AfterSalahEntry[] = (["Fajr", "Dhuhr", "Asr", "Maghrib", "Isha"] as const).map((s) => ({
    salah: s,
    collectionId: "col_salah",
    items: s === "Fajr" ? [{ contentId: content[1].id, order: 1, required: false }] : [],
  }))

  const featured: FeaturedEntry[] = [
    { id: "feat_1", kind: "dua", contentId: content[0].id, displayOrder: 1, startDate: "", endDate: "" },
    { id: "feat_2", kind: "quranic", contentId: content[5].id, displayOrder: 2, startDate: "", endDate: "" },
    { id: "feat_3", kind: "rabbana", contentId: content[6].id, displayOrder: 3, startDate: "", endDate: "" },
  ]

  const milestones: Milestone[] = [
    { id: "ms_1", name: "First Complete Journey", description: "Complete the full daily journey once.", threshold: 1, active: true },
    { id: "ms_2", name: "7-Day Completion", description: "Complete the daily journey 7 days in a row.", threshold: 7, active: true },
    { id: "ms_3", name: "30-Day Completion", description: "Complete the daily journey 30 days in a row.", threshold: 30, active: true },
    { id: "ms_4", name: "100 Completed Sessions", description: "Complete 100 journey sessions.", threshold: 100, active: true },
  ]

  const settings: TheoSettings = {
    defaultCategories: categories.map((x) => x.id),
    defaultJourney: journey.sections.map((s) => s.key),
    verificationRequired: true,
    publicationRules: "Arabic, Translation and Reference are required before publishing.",
    displayRules: "Verified content appears in user dashboard; drafts and archived are hidden.",
    defaultOrdering: "displayOrder",
  }

  return {
    content,
    categories,
    subcategories,
    collections,
    references,
    tags,
    journey,
    afterSalah,
    featured,
    milestones,
    settings,
  }
}
