import type {
  AnyContent,
  AuditLog,
  BackupRecord,
  BadgeRule,
  BookContent,
  Category,
  InfographicContent,
  ApiKey,
  MediaAsset,
  MembershipPlan,
  NotificationRecord,
  PaymentRecord,
  PlatformId,
  PodcastEpisode,
  Region,
  ResearchContent,
  RssFeed,
  ServiceRecord,
  SocialLink,
  SystemHealth,
  Tag,
  Topic,
  UserRecord,
} from "./types"
import { PLATFORM_CATEGORIES } from "./platforms"

const now = new Date().toISOString()
const daysAgo = (d: number) =>
  new Date(Date.now() - d * 86400000).toISOString()
const daysAhead = (d: number) =>
  new Date(Date.now() + d * 86400000).toISOString()

let n = 0
const uid = (p: string) => `${p}_${(++n).toString().padStart(4, "0")}`

function defaultSeo(title: string, slug: string) {
  return {
    seoTitle: title,
    metaDescription: `${title} — published on .Gate across the unified knowledge ecosystem.`,
    focusKeyword: slug.split("-")[0] ?? "gate",
    slug,
    canonicalUrl: `https://gate.app/${slug}`,
    ogTitle: title,
    ogDescription: `${title} on .Gate.`,
    ogImage: "",
    twitterCard: "summary_large_image" as const,
    schemaType: "Article",
    robots: "index,follow",
    aeoSummary: `${title} is part of the .Gate knowledge ecosystem.`,
    faq: [],
  }
}

/* ----------------------------- CONTENT ----------------------------- */

const books: BookContent[] = [
  {
    id: uid("bk"),
    type: "book",
    platform: "IPN",
    title: "The Attention Republic: Reclaiming the Public Mind",
    slug: "attention-republic",
    status: "published",
    category: "Society",
    subcategory: "Media & Culture",
    tags: ["attention", "media", "society", "policy"],
    regions: ["Global"],
    topics: ["Public Discourse"],
    featured: true,
    pinned: false,
    displayOrder: 1,
    views: 18420,
    shares: 2310,
    bookmarks: 1870,
    createdAt: daysAgo(60),
    updatedAt: daysAgo(4),
    publishedAt: daysAgo(40),
    author: "Dr. Zayd Haji",
    description:
      "A sweeping examination of how attention has become the defining resource of the 21st century, and what societies can do to protect the public mind from manipulation. Drawing on behavioural science, political economy and media theory, the book proposes a practical framework for rebuilding trustworthy information environments.",
    cover: "",
    subtitle: "How Information Empires Shape What We Believe",
    pdfUrl: "",
    publicationInfo: "First edition · 2024 · .Gate Press",
    purchaseLinks: {
      paperback: { enabled: true, url: "https://amazon.in/dp/example" },
      ebook: { enabled: true, url: "https://notionpress.com/example" },
      amazon: { enabled: true, url: "https://amazon.in/dp/example" },
      notionPress: { enabled: true, url: "https://notionpress.com/example" },
      googlePlayBooks: {
        enabled: true,
        url: "https://play.google.com/store/books/details/example",
      },
      other: { enabled: false, url: "" },
    },
    freeSampleEnabled: true,
    freeSamplePdf: "",
    seo: defaultSeo(
      "The Attention Republic",
      "ipn/books/the-attention-republic",
    ),
    feedPlacement: "top",
  },
  {
    id: uid("bk"),
    type: "book",
    platform: "IGC",
    title: "The 1% Better Framework",
    slug: "one-percent-better",
    status: "published",
    category: "Productivity & Time Management",
    tags: ["productivity", "habits", "growth"],
    regions: ["Global"],
    topics: ["Personal Mastery"],
    featured: true,
    pinned: true,
    displayOrder: 1,
    views: 22110,
    shares: 3120,
    bookmarks: 2400,
    createdAt: daysAgo(50),
    updatedAt: daysAgo(2),
    publishedAt: daysAgo(30),
    author: "Dr. Zayd Haji",
    description:
      "Small, deliberate improvements compound into remarkable outcomes. This field guide gives professionals a repeatable system for measuring, protecting and growing their most valuable asset — focused time.",
    cover: "",
    subtitle: "A System for Lifelong Productivity",
    pdfUrl: "",
    publicationInfo: "First edition · 2024",
    purchaseLinks: {
      paperback: { enabled: true, url: "" },
      ebook: { enabled: true, url: "" },
      amazon: { enabled: false, url: "" },
      notionPress: { enabled: true, url: "" },
      googlePlayBooks: { enabled: true, url: "" },
      other: { enabled: false, url: "" },
    },
    freeSampleEnabled: true,
    freeSamplePdf: "",
    seo: defaultSeo("The 1% Better Framework", "igc/books/one-percent-better"),
    feedPlacement: "default",
  },
  {
    id: uid("bk"),
    type: "book",
    platform: "IFR",
    title: "Ethical Markets: A Primer on Shariah-Aligned Finance",
    slug: "ethical-markets",
    status: "published",
    category: "Ethical Finance",
    tags: ["finance", "ethics", "investing"],
    regions: ["Global"],
    topics: ["Capital Markets"],
    featured: false,
    pinned: false,
    displayOrder: 2,
    views: 9800,
    shares: 870,
    bookmarks: 720,
    createdAt: daysAgo(80),
    updatedAt: daysAgo(10),
    publishedAt: daysAgo(55),
    author: "Dr. Zayd Haji",
    description:
      "An accessible introduction to how Islamic finance principles map onto modern capital markets, with case studies on sukuk, profit-sharing and risk-sharing instruments.",
    cover: "",
    subtitle: "Principles for a Fairer Economy",
    pdfUrl: "",
    publicationInfo: "First edition · 2023",
    purchaseLinks: {
      paperback: { enabled: false, url: "" },
      ebook: { enabled: true, url: "" },
      amazon: { enabled: false, url: "" },
      notionPress: { enabled: true, url: "" },
      googlePlayBooks: { enabled: true, url: "" },
      other: { enabled: false, url: "" },
    },
    freeSampleEnabled: false,
    seo: defaultSeo("Ethical Markets", "ifr/books/ethical-markets"),
    feedPlacement: "default",
  },
  {
    id: uid("bk"),
    type: "book",
    platform: "ISR",
    title: "Tafsir for the Contemporary Mind",
    slug: "tafsir-contemporary-mind",
    status: "published",
    category: "Tafsir Ibn Kathir",
    tags: ["tafsir", "quran", "reflection"],
    regions: ["Global"],
    topics: ["Scripture"],
    featured: true,
    pinned: false,
    displayOrder: 1,
    views: 31200,
    shares: 5400,
    bookmarks: 4100,
    createdAt: daysAgo(120),
    updatedAt: daysAgo(1),
    publishedAt: daysAgo(90),
    author: "Dr. Zayd Haji",
    description:
      "A thematic journey through selected chapters of the Qur'an, bridging classical exegesis with the questions of modern life — meaning, purpose, ethics and community.",
    cover: "",
    subtitle: "Reflections on Selected Chapters",
    pdfUrl: "",
    publicationInfo: "First edition · 2024",
    purchaseLinks: {
      paperback: { enabled: true, url: "" },
      ebook: { enabled: true, url: "" },
      amazon: { enabled: true, url: "" },
      notionPress: { enabled: true, url: "" },
      googlePlayBooks: { enabled: true, url: "" },
      other: { enabled: false, url: "" },
    },
    freeSampleEnabled: true,
    freeSamplePdf: "",
    seo: defaultSeo(
      "Tafsir for the Contemporary Mind",
      "isr/books/tafsir-contemporary-mind",
    ),
    feedPlacement: "top",
  },
  {
    id: uid("bk"),
    type: "book",
    platform: "IPN",
    title: "Climate Diplomacy After the Tipping Point",
    slug: "climate-diplomacy",
    status: "draft",
    category: "Environment & Climate",
    tags: ["climate", "policy", "diplomacy"],
    regions: ["Global"],
    topics: ["Governance"],
    featured: false,
    pinned: false,
    displayOrder: 3,
    views: 0,
    shares: 0,
    bookmarks: 0,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(1),
    author: "Dr. Zayd Haji",
    description:
      "Draft manuscript exploring the new architecture of international climate negotiation.",
    cover: "",
    purchaseLinks: {
      paperback: { enabled: false, url: "" },
      ebook: { enabled: false, url: "" },
      amazon: { enabled: false, url: "" },
      notionPress: { enabled: false, url: "" },
      googlePlayBooks: { enabled: false, url: "" },
      other: { enabled: false, url: "" },
    },
    freeSampleEnabled: false,
    seo: defaultSeo("Climate Diplomacy", "ipn/books/climate-diplomacy"),
    feedPlacement: "default",
  },
]

const research: ResearchContent[] = [
  {
    id: uid("rr"),
    type: "research",
    platform: "IFR",
    title: "State of Ethical Banking 2025",
    slug: "state-ethical-banking-2025",
    status: "published",
    category: "Ethical Banking",
    tags: ["banking", "report", "2025"],
    regions: ["Global"],
    topics: ["Financial Systems"],
    featured: true,
    pinned: false,
    displayOrder: 1,
    views: 7600,
    shares: 540,
    bookmarks: 430,
    createdAt: daysAgo(40),
    updatedAt: daysAgo(3),
    publishedAt: daysAgo(20),
    author: ".Gate Research Desk",
    description:
      "Our annual benchmark of 40 institutions ranked on transparency, risk-sharing products and community reinvestment. Includes methodology, scoring and policy recommendations for regulators.",
    cover: "",
    subtitle: "Annual Benchmark Report",
    pdfUrl: "",
    publicationInfo: "IFR Research · Vol 3",
    purchaseLinks: {
      paperback: { enabled: false, url: "" },
      ebook: { enabled: false, url: "" },
      amazon: { enabled: false, url: "" },
      notionPress: { enabled: false, url: "" },
      googlePlayBooks: { enabled: true, url: "" },
      other: { enabled: false, url: "" },
    },
    freeSampleEnabled: true,
    freeSamplePdf: "",
    seo: defaultSeo(
      "State of Ethical Banking 2025",
      "ifr/research/state-ethical-banking-2025",
    ),
    feedPlacement: "default",
  },
  {
    id: uid("rr"),
    type: "research",
    platform: "IPN",
    title: "Global Misinformation Index 2025",
    slug: "global-misinformation-index-2025",
    status: "published",
    category: "Politics & Governance",
    tags: ["misinformation", "index", "policy"],
    regions: ["Global"],
    topics: ["Public Discourse"],
    featured: false,
    pinned: false,
    displayOrder: 2,
    views: 11200,
    shares: 980,
    bookmarks: 760,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(6),
    publishedAt: daysAgo(14),
    author: ".Gate Research Desk",
    description:
      "A cross-country index measuring exposure, resilience and policy response to coordinated misinformation campaigns.",
    cover: "",
    subtitle: "Cross-National Policy Study",
    pdfUrl: "",
    publicationInfo: "IPN Research · Vol 7",
    purchaseLinks: {
      paperback: { enabled: false, url: "" },
      ebook: { enabled: false, url: "" },
      amazon: { enabled: false, url: "" },
      notionPress: { enabled: false, url: "" },
      googlePlayBooks: { enabled: true, url: "" },
      other: { enabled: false, url: "" },
    },
    freeSampleEnabled: false,
    seo: defaultSeo(
      "Global Misinformation Index 2025",
      "ipn/research/global-misinformation-index-2025",
    ),
    feedPlacement: "default",
  },
  {
    id: uid("rr"),
    type: "research",
    platform: "ISR",
    title: "Hadith Transmission Chains: A Data Study",
    slug: "hadith-transmission-chains",
    status: "scheduled",
    category: "Hadith Studies",
    tags: ["hadith", "data", "methodology"],
    regions: ["Global"],
    topics: ["Scripture"],
    featured: false,
    pinned: false,
    displayOrder: 2,
    views: 0,
    shares: 0,
    bookmarks: 0,
    createdAt: daysAgo(8),
    updatedAt: daysAgo(2),
    scheduledAt: daysAhead(3),
    author: ".Gate Research Desk",
    description:
      "Applying network analysis to the isnad literature to visualise how collections relate.",
    cover: "",
    subtitle: "Quantitative Methodology Paper",
    pdfUrl: "",
    publicationInfo: "ISR Research · Vol 2",
    purchaseLinks: {
      paperback: { enabled: false, url: "" },
      ebook: { enabled: false, url: "" },
      amazon: { enabled: false, url: "" },
      notionPress: { enabled: false, url: "" },
      googlePlayBooks: { enabled: true, url: "" },
      other: { enabled: false, url: "" },
    },
    freeSampleEnabled: false,
    seo: defaultSeo(
      "Hadith Transmission Chains",
      "isr/research/hadith-transmission-chains",
    ),
    feedPlacement: "default",
  },
]

const infographics: InfographicContent[] = [
  {
    id: uid("ig"),
    type: "infographic",
    platform: "IPN",
    title: "How Your Feed Decides Your Mood",
    slug: "feed-mood",
    status: "published",
    category: "Society",
    subcategory: "Media & Culture",
    tags: ["attention", "social", "psychology"],
    regions: ["Global"],
    topics: ["Public Discourse"],
    featured: true,
    pinned: false,
    displayOrder: 1,
    views: 45200,
    shares: 6200,
    bookmarks: 3900,
    createdAt: daysAgo(20),
    updatedAt: daysAgo(2),
    publishedAt: daysAgo(12),
    description:
      "A visual breakdown of the algorithmic loop between scrolling, dopamine and emotional state — and three small habits to reclaim agency over your feed.",
    image: "",
    caption:
      "Every scroll is a small vote for the kind of mind you want to have. This infographic maps the loop and offers three practical interruptions.",
    seo: defaultSeo("How Your Feed Decides Your Mood", "ipn/infographics/feed-mood"),
    feedPlacement: "top",
  },
  {
    id: uid("ig"),
    type: "infographic",
    platform: "IFR",
    title: "The Anatomy of a Sukuk",
    slug: "anatomy-of-sukuk",
    status: "published",
    category: "Ethical Finance",
    tags: ["sukuk", "investing", "basics"],
    regions: ["Global"],
    topics: ["Capital Markets"],
    featured: false,
    pinned: false,
    displayOrder: 2,
    views: 18900,
    shares: 2100,
    bookmarks: 1700,
    createdAt: daysAgo(25),
    updatedAt: daysAgo(5),
    publishedAt: daysAgo(18),
    description:
      "Step-by-step visual explainer of how asset-backed Islamic bonds work compared with conventional debt.",
    image: "",
    caption:
      "Sukuk represent proportional ownership of an underlying asset. This infographic walks through the structure, cash flows and risk profile.",
    seo: defaultSeo("The Anatomy of a Sukuk", "ifr/infographics/anatomy-of-sukuk"),
    feedPlacement: "default",
  },
  {
    id: uid("ig"),
    type: "infographic",
    platform: "IGC",
    title: "The 5-Minute Reset for Deep Work",
    slug: "five-minute-reset",
    status: "published",
    category: "Productivity & Time Management",
    tags: ["focus", "habits", "work"],
    regions: ["Global"],
    topics: ["Personal Mastery"],
    featured: true,
    pinned: false,
    displayOrder: 1,
    views: 33800,
    shares: 4800,
    bookmarks: 3100,
    createdAt: daysAgo(15),
    updatedAt: daysAgo(1),
    publishedAt: daysAgo(9),
    description:
      "A simple visual ritual to reset attention between tasks and protect your deepest work blocks.",
    image: "",
    caption:
      "Before your next focus block, spend five minutes on this reset. The infographic shows the exact sequence.",
    seo: defaultSeo("The 5-Minute Reset", "igc/infographics/five-minute-reset"),
    feedPlacement: "default",
  },
  {
    id: uid("ig"),
    type: "infographic",
    platform: "ISR",
    title: "A Map of the Qur'anic Sciences",
    slug: "map-quranic-sciences",
    status: "published",
    category: "Quranic Studies",
    tags: ["quran", "study", "map"],
    regions: ["Global"],
    topics: ["Scripture"],
    featured: false,
    pinned: false,
    displayOrder: 2,
    views: 27600,
    shares: 3900,
    bookmarks: 2900,
    createdAt: daysAgo(18),
    updatedAt: daysAgo(3),
    publishedAt: daysAgo(11),
    description:
      "A visual map linking tafsir, recitation, linguistic sciences and thematic study into one learning path.",
    image: "",
    caption:
      "Where do you begin with the Qur'anic sciences? This map connects the major disciplines into a single journey.",
    seo: defaultSeo(
      "A Map of the Qur'anic Sciences",
      "isr/infographics/map-quranic-sciences",
    ),
    feedPlacement: "default",
  },
]

const podcasts: PodcastEpisode[] = [
  {
    id: uid("pe"),
    type: "podcast",
    platform: "IPN",
    title: "The Public Mind in the Age of Feeds",
    slug: "ipn-public-mind",
    status: "published",
    category: "Society",
    subcategory: "Media & Culture",
    tags: ["attention", "media", "society"],
    regions: ["Global"],
    topics: ["Public Discourse"],
    featured: true,
    pinned: false,
    displayOrder: 1,
    views: 12400,
    shares: 1500,
    bookmarks: 980,
    createdAt: daysAgo(22),
    updatedAt: daysAgo(2),
    publishedAt: daysAgo(14),
    description:
      "A conversation on how information ecosystems shape collective reasoning, and what institutions can do to defend the public mind.",
    artwork: "",
    audioUrl:
      "https://anchor.fm/s/1154f5ab8/podcast/play/1234567/episode-ipn-public-mind.mp3",
    duration: "38:24",
    episodeNumber: 42,
    season: 2,
    rssGuid: "ipn-ep-42-public-mind",
    originalTitle: "The Public Mind in the Age of Feeds",
    originalDescription:
      "Original RSS description for episode 42 of the IPN feed.",
    feedId: "rss_ipn",
    explicit: false,
    seo: defaultSeo("The Public Mind in the Age of Feeds", "ipn/podcasts/public-mind"),
    feedPlacement: "default",
  },
  {
    id: uid("pe"),
    type: "podcast",
    platform: "IGC",
    title: "Building a Career That Compounds",
    slug: "igc-career-compounds",
    status: "published",
    category: "Career Development",
    tags: ["career", "growth", "skills"],
    regions: ["Global"],
    topics: ["Personal Mastery"],
    featured: false,
    pinned: false,
    displayOrder: 2,
    views: 9800,
    shares: 1100,
    bookmarks: 720,
    createdAt: daysAgo(19),
    updatedAt: daysAgo(4),
    publishedAt: daysAgo(13),
    description:
      "Practical frameworks for treating your career like an investment portfolio that compounds over decades.",
    artwork: "",
    audioUrl:
      "https://anchor.fm/s/109d1667c/podcast/play/2234567/episode-igc-career.mp3",
    duration: "41:10",
    episodeNumber: 28,
    season: 1,
    rssGuid: "igc-ep-28-career",
    originalTitle: "Building a Career That Compounds",
    originalDescription:
      "Original RSS description for episode 28 of the IGC feed.",
    feedId: "rss_igc",
    explicit: false,
    seo: defaultSeo(
      "Building a Career That Compounds",
      "igc/podcasts/career-compounds",
    ),
    feedPlacement: "default",
  },
  {
    id: uid("pe"),
    type: "podcast",
    platform: "IFR",
    title: "What Makes Finance Ethical?",
    slug: "ifr-ethical-finance",
    status: "published",
    category: "Ethical Finance",
    tags: ["finance", "ethics", "markets"],
    regions: ["Global"],
    topics: ["Capital Markets"],
    featured: true,
    pinned: false,
    displayOrder: 1,
    views: 7600,
    shares: 820,
    bookmarks: 540,
    createdAt: daysAgo(17),
    updatedAt: daysAgo(3),
    publishedAt: daysAgo(10),
    description:
      "A clear conversation on risk-sharing, transparency and the difference between compliant and genuinely ethical finance.",
    artwork: "",
    audioUrl:
      "https://anchor.fm/s/e7ad1b40/podcast/play/3234567/episode-ifr-ethical.mp3",
    duration: "35:52",
    episodeNumber: 33,
    season: 2,
    rssGuid: "ifr-ep-33-ethical",
    originalTitle: "What Makes Finance Ethical?",
    originalDescription:
      "Original RSS description for episode 33 of the IFR feed.",
    feedId: "rss_ifr",
    explicit: false,
    seo: defaultSeo("What Makes Finance Ethical?", "ifr/podcasts/ethical-finance"),
    feedPlacement: "default",
  },
  {
    id: uid("pe"),
    type: "podcast",
    platform: "ISR",
    title: "Reading the Qur'an With the Times",
    slug: "isr-reading-quran",
    status: "published",
    category: "Contemporary Theological Issues",
    tags: ["quran", "contemporary", "reflection"],
    regions: ["Global"],
    topics: ["Scripture"],
    featured: false,
    pinned: false,
    displayOrder: 2,
    views: 14300,
    shares: 1900,
    bookmarks: 1400,
    createdAt: daysAgo(16),
    updatedAt: daysAgo(1),
    publishedAt: daysAgo(8),
    description:
      "How classical exegesis can speak to modern questions of identity, ethics and community without losing its rootedness.",
    artwork: "",
    audioUrl:
      "https://anchor.fm/s/f49f1ccc/podcast/play/4234567/episode-isr-reading.mp3",
    duration: "44:18",
    episodeNumber: 51,
    season: 3,
    rssGuid: "isr-ep-51-reading",
    originalTitle: "Reading the Qur'an With the Times",
    originalDescription:
      "Original RSS description for episode 51 of the ISR feed.",
    feedId: "rss_isr",
    explicit: false,
    seo: defaultSeo(
      "Reading the Qur'an With the Times",
      "isr/podcasts/reading-quran",
    ),
    feedPlacement: "default",
  },
  {
    id: uid("pe"),
    type: "podcast",
    platform: "ISR",
    title: "Creed and Theology: Foundations",
    slug: "isr-creed-foundations",
    status: "draft",
    category: "Creed and Theology",
    tags: ["creed", "theology", "basics"],
    regions: ["Global"],
    topics: ["Scripture"],
    featured: false,
    pinned: false,
    displayOrder: 3,
    views: 0,
    shares: 0,
    bookmarks: 0,
    createdAt: daysAgo(4),
    updatedAt: daysAgo(1),
    description:
      "Fetched from RSS but awaiting editorial categorisation and review before publish.",
    artwork: "",
    audioUrl:
      "https://anchor.fm/s/f49f1ccc/podcast/play/4234599/episode-isr-creed.mp3",
    duration: "39:05",
    episodeNumber: 52,
    season: 3,
    rssGuid: "isr-ep-52-creed",
    originalTitle: "Creed and Theology: Foundations",
    originalDescription:
      "Original RSS description for episode 52 of the ISR feed.",
    feedId: "rss_isr",
    explicit: false,
    seo: defaultSeo("Creed and Theology: Foundations", "isr/podcasts/creed-foundations"),
    feedPlacement: "default",
  },
]

/* ----------------------------- RSS FEEDS ----------------------------- */

const rssFeeds: RssFeed[] = [
  {
    id: "rss_ipn",
    platform: "IPN",
    title: "IPN | International Public Network",
    url: "https://anchor.fm/s/1154f5ab8/podcast/rss",
    lastSync: daysAgo(0.1),
    status: "healthy",
    totalEpisodes: 52,
    newLastSync: 0,
    autoSync: true,
    frequency: "Every 30 minutes",
  },
  {
    id: "rss_igc",
    platform: "IGC",
    title: "IGC | Inspire Guide Connect",
    url: "https://anchor.fm/s/109d1667c/podcast/rss",
    lastSync: daysAgo(0.2),
    status: "healthy",
    totalEpisodes: 38,
    newLastSync: 1,
    autoSync: true,
    frequency: "Every 30 minutes",
  },
  {
    id: "rss_ifr",
    platform: "IFR",
    title: "IFR | Integrity Finance Research",
    url: "https://anchor.fm/s/e7ad1b40/podcast/rss",
    lastSync: daysAgo(0.3),
    status: "degraded",
    totalEpisodes: 41,
    newLastSync: 0,
    autoSync: true,
    frequency: "Every 30 minutes",
  },
  {
    id: "rss_isr",
    platform: "ISR",
    title: "ISR | Ideological Studies Research",
    url: "https://anchor.fm/s/f49f1ccc/podcast/rss",
    lastSync: daysAgo(0.05),
    status: "healthy",
    totalEpisodes: 63,
    newLastSync: 2,
    autoSync: true,
    frequency: "Every 30 minutes",
  },
]

/* ----------------------------- USERS ----------------------------- */

const userNames = [
  "Aisha Rahman",
  "Karthik Nair",
  "Fatima Sheikh",
  "Daniel Okafor",
  "Mei Lin",
  "Omar Farooq",
  "Sofia Rossi",
  "Raj Patel",
  "Layla Hassan",
  "Tom Becker",
  "Priya Nair",
  "Yusuf Demir",
]

const users: UserRecord[] = userNames.map((name, i) => {
  const membership: UserRecord["membership"] =
    i % 3 === 0 ? "active" : i % 3 === 1 ? "expired" : i % 5 === 0 ? "lifetime" : "none"
  return {
    id: `usr_${(i + 1).toString().padStart(4, "0")}`,
    name,
    email: name.toLowerCase().replace(/[^a-z]+/g, ".") + "@example.com",
    avatarColor: [
      "#0ea5e9",
      "#10b981",
      "#f59e0b",
      "#8b5cf6",
      "#ec4899",
      "#14b8a6",
    ][i % 6],
    provider: i % 4 === 0 ? "google" : i % 5 === 0 ? "apple" : "email",
    verified: i % 7 !== 0,
    membership,
    plan:
      membership === "active"
        ? i % 2 === 0
          ? "1 Year"
          : "Monthly"
        : membership === "lifetime"
          ? "Lifetime"
          : undefined,
    accountStatus: i % 9 === 0 ? "suspended" : "active",
    role: i === 0 ? "admin" : i % 6 === 0 ? "editor" : "user",
    joinedAt: daysAgo(120 - i * 7),
    lastActive: daysAgo(i % 5),
    bookmarks: Math.round(20 + Math.random() * 200),
    downloads: Math.round(5 + Math.random() * 80),
    readingHours: Math.round(10 + Math.random() * 200),
    listeningHours: Math.round(5 + Math.random() * 150),
    interests: ["Finance", "Theology", "Productivity"].slice(0, (i % 3) + 1),
    followedCategories: ["Society", "Ethical Finance", "Quranic Studies"].slice(
      0,
      (i % 3) + 1,
    ),
  }
})

/* ----------------------------- MEMBERSHIP PLANS ----------------------------- */

const membershipPlans: MembershipPlan[] = [
  {
    id: "plan_monthly",
    name: "Monthly",
    durationLabel: "Monthly",
    priceINR: 99,
    benefits: [
      "Full premium access",
      "All books, podcasts, infographics, research",
      "Cancel anytime",
    ],
    active: true,
    entitlements: "all",
  },
  {
    id: "plan_1y",
    name: "1 Year",
    durationLabel: "1 Year",
    priceINR: 799,
    popular: true,
    benefits: [
      "Everything in Monthly",
      "Save over 32% vs monthly",
      "Offline downloads",
    ],
    active: true,
    entitlements: "all",
  },
  {
    id: "plan_3y",
    name: "3 Years",
    durationLabel: "3 Years",
    priceINR: 2199,
    benefits: ["Everything in 1 Year", "Greatest long-term value"],
    active: true,
    entitlements: "all",
  },
  {
    id: "plan_5y",
    name: "5 Years",
    durationLabel: "5 Years",
    priceINR: 3499,
    benefits: ["Everything in 3 Years", "Locked-in lower pricing"],
    active: true,
    entitlements: "all",
  },
  {
    id: "plan_7y",
    name: "7 Years",
    durationLabel: "7 Years",
    priceINR: 4699,
    benefits: ["Everything in 5 Years", "Commitment pricing"],
    active: true,
    entitlements: "all",
  },
  {
    id: "plan_9y",
    name: "9 Years",
    durationLabel: "9 Years",
    priceINR: 5799,
    benefits: ["Everything in 7 Years", "Legacy pricing"],
    active: true,
    entitlements: "all",
  },
  {
    id: "plan_lifetime",
    name: "Lifetime",
    durationLabel: "One-time",
    priceINR: 9999,
    benefits: ["Pay once. Learn for a lifetime.", "All future content included"],
    active: true,
    entitlements: "all",
  },
]

/* ----------------------------- PAYMENTS ----------------------------- */

const payments: PaymentRecord[] = Array.from({ length: 24 }).map((_, i) => {
  const plans = ["Monthly", "1 Year", "3 Years", "Lifetime"]
  const plan = plans[i % plans.length]
  const priceMap: Record<string, number> = {
    Monthly: 99,
    "1 Year": 799,
    "3 Years": 2199,
    Lifetime: 9999,
  }
  const status: PaymentRecord["status"] =
    i % 11 === 0 ? "failed" : i % 13 === 0 ? "refunded" : i % 17 === 0 ? "pending" : "success"
  const u = users[i % users.length]
  return {
    id: `pay_${(i + 1).toString().padStart(5, "0")}`,
    userId: u.id,
    userName: u.name,
    plan,
    amount: priceMap[plan],
    currency: "INR",
    status,
    method: i % 2 === 0 ? "UPI" : "Card",
    provider: "GatePay",
    transactionRef: `GT-${Date.now().toString().slice(-6)}${i}`,
    createdAt: daysAgo(i * 3),
    membershipType: plan === "Lifetime" ? "lifetime" : "subscription",
  }
})

/* ----------------------------- TAXONOMY ----------------------------- */

const categories: Category[] = []
;(Object.keys(PLATFORM_CATEGORIES) as PlatformId[]).forEach((pid) => {
  PLATFORM_CATEGORIES[pid].forEach((name, idx) => {
    categories.push({
      id: `cat_${pid}_${idx}`,
      platform: pid,
      name,
      slug: name.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
      description: `${name} content within ${pid}.`,
      displayOrder: idx + 1,
      status: "active",
      icon: "folder",
      contentCount: Math.round(2 + Math.random() * 40),
    })
  })
})

const tags: Tag[] = [
  "attention",
  "media",
  "society",
  "policy",
  "finance",
  "ethics",
  "productivity",
  "habits",
  "growth",
  "quran",
  "tafsir",
  "hadith",
  "climate",
  "career",
  "investing",
  "reflection",
  "misinformation",
  "focus",
].map((t, i) => ({
  id: `tag_${i}`,
  name: t,
  slug: t,
  usage: Math.round(3 + Math.random() * 60),
  platform: "ALL",
}))

const regions: Region[] = [
  ...[
    "South Asia",
    "Middle East",
    "Europe",
    "Africa",
    "North America",
    "Southeast Asia",
  ].map((r) => ({
    id: `reg_${r}`,
    name: r,
    slug: r.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    type: "regional" as const,
    usage: Math.round(5 + Math.random() * 50),
  })),
  ...[
    "Global",
    "United Nations",
    "G20",
    "BRICS",
    "ASEAN",
    "European Union",
  ].map((r) => ({
    id: `reg_${r}`,
    name: r,
    slug: r.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
    type: "international" as const,
    usage: Math.round(10 + Math.random() * 80),
  })),
]

const topics: Topic[] = [
  "Public Discourse",
  "Personal Mastery",
  "Capital Markets",
  "Scripture",
  "Governance",
  "Financial Systems",
].map((t, i) => ({
  id: `topic_${i}`,
  name: t,
  slug: t.toLowerCase().replace(/[^a-z0-9]+/g, "-"),
  usage: Math.round(8 + Math.random() * 90),
}))

/* ----------------------------- SERVICES ----------------------------- */

const services: ServiceRecord[] = [
  {
    id: uid("svc"),
    platform: "IPN",
    category: "Public Affairs",
    title: "Advertising & Sponsored Insights",
    slug: "ipn-advertising",
    shortDescription:
      "Reach a high-intent, knowledge-driven audience across the IPN network.",
    fullDescription:
      "IPN offers brand-safe sponsored content, infographic boosts and newsletter placements to organisations aligned with our editorial standards.",
    benefits: ["Brand-safe placement", "Audience insights", "Custom creative"],
    pricingMode: "contact",
    pricingText: "Custom quote based on reach and format.",
    whatsappUrl: "wa.link/f44l0k",
    externalUrl: "",
    seoTitle: "Advertising on IPN",
    status: "published",
    displayOrder: 1,
    featured: true,
    updatedAt: daysAgo(3),
  },
  {
    id: uid("svc"),
    platform: "IPN",
    category: "Research",
    title: "Research Reports",
    slug: "ipn-research-reports",
    shortDescription:
      "Commissioned, methodology-led research on public policy and society.",
    fullDescription:
      "Work with the .Gate Research Desk to produce rigorous, citable reports on the topics that matter to your organisation.",
    benefits: ["Rigorous methodology", "Citable outputs", "Data visualisation"],
    pricingMode: "contact",
    pricingText: "Project-based pricing.",
    whatsappUrl: "wa.link/f44l0k",
    externalUrl: "",
    seoTitle: "IPN Research Reports",
    status: "published",
    displayOrder: 2,
    featured: false,
    updatedAt: daysAgo(5),
  },
  {
    id: uid("svc"),
    platform: "IGC",
    category: "Workshops",
    title: "Career & Employability Workshops",
    slug: "igc-career-workshops",
    shortDescription:
      "Live online and offline workshops on employability and growth.",
    fullDescription:
      "Hands-on sessions covering résumé building, interviews, negotiation and long-term career design.",
    benefits: ["Live sessions", "Templates", "Certificate"],
    pricingMode: "paid",
    pricingText: "From ₹499 per seat.",
    whatsappUrl: "wa.link/f44l0k",
    externalUrl: "",
    seoTitle: "IGC Career Workshops",
    status: "published",
    displayOrder: 1,
    featured: true,
    updatedAt: daysAgo(2),
  },
  {
    id: uid("svc"),
    platform: "IFR",
    category: "Research",
    title: "Financial Literacy Workshops",
    slug: "ifr-financial-literacy",
    shortDescription:
      "Practical financial education rooted in ethical finance principles.",
    fullDescription:
      "Workshops for professionals, students and institutions on budgeting, investing and ethical products.",
    benefits: ["Practical frameworks", "Live Q&A", "Resources"],
    pricingMode: "contact",
    pricingText: "Custom quote.",
    whatsappUrl: "wa.link/f44l0k",
    externalUrl: "",
    seoTitle: "IFR Financial Literacy",
    status: "published",
    displayOrder: 1,
    featured: false,
    updatedAt: daysAgo(6),
  },
  {
    id: uid("svc"),
    platform: "ISR",
    category: "Workshops",
    title: "Theological Live Workshops",
    slug: "isr-theological-workshops",
    shortDescription:
      "Live online and offline workshops on Quranic studies.",
    fullDescription:
      "Guided study circles and lectures on tafsir, hadith and contemporary theology.",
    benefits: ["Expert facilitation", "Recordings", "Community"],
    pricingMode: "contact",
    pricingText: "Custom quote.",
    whatsappUrl: "wa.link/f44l0k",
    externalUrl: "",
    seoTitle: "ISR Theological Workshops",
    status: "published",
    displayOrder: 1,
    featured: true,
    updatedAt: daysAgo(1),
  },
  {
    id: uid("svc"),
    platform: "ISR",
    category: "Support",
    title: "Patrons & Donations",
    slug: "isr-patrons",
    shortDescription: "Support independent theological research.",
    fullDescription:
      "Become a patron and help sustain open, rigorous scholarship.",
    benefits: ["Recognised support", "Early access"],
    pricingMode: "free",
    pricingText: "Donations welcome.",
    whatsappUrl: "wa.link/f44l0k",
    externalUrl: "",
    seoTitle: "ISR Patrons",
    status: "published",
    displayOrder: 2,
    featured: false,
    updatedAt: daysAgo(4),
  },
]

/* ----------------------------- SOCIAL LINKS ----------------------------- */

const socialLinks: SocialLink[] = [
  {
    id: uid("sl"),
    platform: "IPN",
    type: "website",
    label: "Website",
    url: "https://www.drzaydhaji.com",
    displayOrder: 1,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IPN",
    type: "x",
    label: "X (Twitter)",
    url: "https://www.x.com/ipngate",
    displayOrder: 2,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IPN",
    type: "instagram",
    label: "Instagram",
    url: "https://www.instagram.com/ipn.gate",
    displayOrder: 3,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IPN",
    type: "facebook",
    label: "Facebook",
    url: "https://www.facebook.com/ipn.gate/",
    displayOrder: 4,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IPN",
    type: "spotify",
    label: "Spotify",
    url: "https://open.spotify.com/show/033VCxjOKlNfHBM1wceTwZ",
    displayOrder: 5,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IPN",
    type: "apple",
    label: "Apple Podcasts",
    url: "https://podcasts.apple.com/us/podcast/ipn/id6794651434",
    displayOrder: 6,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IPN",
    type: "linkedin",
    label: "LinkedIn",
    url: "https://www.linkedin.com/company/ipngate/",
    displayOrder: 7,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IPN",
    type: "whatsapp_community",
    label: "WhatsApp Community",
    url: "https://chat.whatsapp.com/KFy7LSrHTRN8el6mB8Nnrk",
    displayOrder: 8,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IPN",
    type: "whatsapp_channel",
    label: "WhatsApp Channel",
    url: "https://whatsapp.com/channel/0029VbDCIAdL2ATxOkziUr19",
    displayOrder: 9,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IPN",
    type: "whatsapp_contact",
    label: "WhatsApp Contact",
    url: "wa.link/f44l0k",
    displayOrder: 10,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IGC",
    type: "website",
    label: "Website",
    url: "https://www.drzaydalhaji.com",
    displayOrder: 1,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IGC",
    type: "x",
    label: "X (Twitter)",
    url: "https://x.com/igcgate",
    displayOrder: 2,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IGC",
    type: "instagram",
    label: "Instagram",
    url: "https://www.instagram.com/igc.gate/",
    displayOrder: 3,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IGC",
    type: "spotify",
    label: "Spotify",
    url: "https://open.spotify.com/show/7goWWp28Ljd7BC5K3Bh4Bb",
    displayOrder: 4,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IGC",
    type: "linkedin",
    label: "LinkedIn",
    url: "https://www.linkedin.com/company/igcgate/",
    displayOrder: 5,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IGC",
    type: "whatsapp_contact",
    label: "WhatsApp Contact",
    url: "wa.link/f44l0k",
    displayOrder: 6,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IFR",
    type: "website",
    label: "Website",
    url: "https://www.zaydhaji.com",
    displayOrder: 1,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IFR",
    type: "x",
    label: "X (Twitter)",
    url: "https://x.com/ifrgate",
    displayOrder: 2,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IFR",
    type: "instagram",
    label: "Instagram",
    url: "https://www.instagram.com/ifr.gate/",
    displayOrder: 3,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IFR",
    type: "spotify",
    label: "Spotify",
    url: "https://open.spotify.com/show/7G5AbdkS2N3d2BBj0RDmuz",
    displayOrder: 4,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IFR",
    type: "linkedin",
    label: "LinkedIn",
    url: "https://www.linkedin.com/company/ifrgate/",
    displayOrder: 5,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "IFR",
    type: "whatsapp_contact",
    label: "WhatsApp Contact",
    url: "wa.link/f44l0k",
    displayOrder: 6,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "ISR",
    type: "website",
    label: "Website",
    url: "https://www.zaydalhaji.com",
    displayOrder: 1,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "ISR",
    type: "x",
    label: "X (Twitter)",
    url: "https://x.com/isrgate",
    displayOrder: 2,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "ISR",
    type: "instagram",
    label: "Instagram",
    url: "https://www.instagram.com/isr.gate/",
    displayOrder: 3,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "ISR",
    type: "spotify",
    label: "Spotify",
    url: "https://open.spotify.com/show/5rF294PWY9uvktx4JD4BTv",
    displayOrder: 4,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "ISR",
    type: "linkedin",
    label: "LinkedIn",
    url: "https://www.linkedin.com/company/isrgate/",
    displayOrder: 5,
    active: true,
  },
  {
    id: uid("sl"),
    platform: "ISR",
    type: "whatsapp_contact",
    label: "WhatsApp Contact",
    url: "wa.link/f44l0k",
    displayOrder: 6,
    active: true,
  },
]

/* ----------------------------- MEDIA ----------------------------- */

const mediaAssets: MediaAsset[] = [
  {
    id: uid("md"),
    name: "attention-republic-cover.jpg",
    folder: "Book Covers",
    type: "image",
    mime: "image/jpeg",
    sizeKB: 184,
    width: 320,
    height: 500,
    altText: "Cover of The Attention Republic",
    url: "",
    uploadedAt: daysAgo(40),
    usedBy: 2,
    hash: "a1b2c3",
  },
  {
    id: uid("md"),
    name: "feed-mood-infographic.jpg",
    folder: "Infographics",
    type: "image",
    mime: "image/jpeg",
    sizeKB: 412,
    width: 1080,
    height: 1350,
    altText: "How your feed decides your mood infographic",
    url: "",
    uploadedAt: daysAgo(12),
    usedBy: 3,
    hash: "d4e5f6",
  },
  {
    id: uid("md"),
    name: "anatomy-sukuk-infographic.jpg",
    folder: "Infographics",
    type: "image",
    mime: "image/jpeg",
    sizeKB: 388,
    width: 1080,
    height: 1350,
    altText: "Anatomy of a sukuk explainer",
    url: "",
    uploadedAt: daysAgo(18),
    usedBy: 1,
    hash: "d4e5f6",
  },
  {
    id: uid("md"),
    name: "tafsir-contemporary-cover.jpg",
    folder: "Book Covers",
    type: "image",
    mime: "image/jpeg",
    sizeKB: 202,
    width: 320,
    height: 500,
    altText: "Tafsir for the Contemporary Mind cover",
    url: "",
    uploadedAt: daysAgo(90),
    usedBy: 4,
    hash: "g7h8i9",
  },
  {
    id: uid("md"),
    name: "state-ethical-banking.pdf",
    folder: "Reports",
    type: "pdf",
    mime: "application/pdf",
    sizeKB: 2400,
    altText: "",
    url: "",
    uploadedAt: daysAgo(20),
    usedBy: 1,
    hash: "j1k2l3",
  },
]

/* ----------------------------- NOTIFICATIONS ----------------------------- */

const notifications: NotificationRecord[] = [
  {
    id: uid("nt"),
    type: "book",
    title: "New Book Published: The Attention Republic",
    body: "A new IPN book is now available for members.",
    platform: "IPN",
    target: "members",
    status: "sent",
    createdAt: daysAgo(4),
    sentAt: daysAgo(4),
  },
  {
    id: uid("nt"),
    type: "podcast",
    title: "New Episode: Reading the Qur'an With the Times",
    body: "Episode 51 of the ISR podcast is live.",
    platform: "ISR",
    target: "all",
    status: "sent",
    createdAt: daysAgo(8),
    sentAt: daysAgo(8),
  },
  {
    id: uid("nt"),
    type: "research",
    title: "Research Report Scheduled",
    body: "Hadith Transmission Chains will publish in 3 days.",
    platform: "ISR",
    target: "members",
    status: "scheduled",
    scheduledAt: daysAhead(3),
    createdAt: daysAgo(2),
  },
  {
    id: uid("nt"),
    type: "renewal",
    title: "Membership Renewal Reminder",
    body: "Your 1 Year membership renews soon.",
    target: "members",
    status: "draft",
    createdAt: daysAgo(1),
  },
]

/* ----------------------------- AUDIT LOGS ----------------------------- */

const auditLogs: AuditLog[] = [
  {
    id: uid("al"),
    actor: "admin@gate.app",
    role: "Super Admin",
    action: "publish",
    resource: "book",
    resourceId: books[0].id,
    timestamp: daysAgo(4),
    ip: "203.0.113.12",
    result: "success",
    detail: "Published 'The Attention Republic' to IPN.",
  },
  {
    id: uid("al"),
    actor: "editor@gate.app",
    role: "Editor",
    action: "edit",
    resource: "infographic",
    resourceId: infographics[0].id,
    timestamp: daysAgo(2),
    ip: "203.0.113.45",
    result: "success",
    detail: "Updated caption for 'How Your Feed Decides Your Mood'.",
  },
  {
    id: uid("al"),
    actor: "admin@gate.app",
    role: "Super Admin",
    action: "rss_sync",
    resource: "podcast",
    resourceId: "rss_isr",
    timestamp: daysAgo(0.05),
    ip: "203.0.113.12",
    result: "success",
    detail: "Synced ISR RSS — 2 new episodes detected.",
  },
  {
    id: uid("al"),
    actor: "system",
    role: "System",
    action: "payment",
    resource: "payment",
    resourceId: payments[0].id,
    timestamp: daysAgo(3),
    ip: "internal",
    result: "success",
    detail: "Payment success activated Monthly membership.",
  },
  {
    id: uid("al"),
    actor: "analyst@gate.app",
    role: "Analyst",
    action: "login",
    resource: "auth",
    resourceId: "analyst@gate.app",
    timestamp: daysAgo(1),
    ip: "198.51.100.7",
    result: "success",
    detail: "Admin login from new device.",
  },
]

/* ----------------------------- BADGE RULES ----------------------------- */

const badgeRules: BadgeRule[] = [
  {
    id: uid("bd"),
    name: "Daily Streak",
    type: "daily_streak",
    description: "Open the app and complete a session 7 days in a row.",
    icon: "flame",
    active: true,
    threshold: 7,
  },
  {
    id: uid("bd"),
    name: "Weekly Streak",
    type: "weekly_streak",
    description: "Maintain activity across 4 weeks.",
    icon: "calendar",
    active: true,
    threshold: 4,
  },
  {
    id: uid("bd"),
    name: "Monthly Streak",
    type: "monthly_streak",
    description: "Stay active for 3 consecutive months.",
    icon: "calendar-days",
    active: true,
    threshold: 3,
  },
  {
    id: uid("bd"),
    name: "Reading Badge",
    type: "reading",
    description: "Finish 10 books.",
    icon: "book-open",
    active: true,
    threshold: 10,
  },
  {
    id: uid("bd"),
    name: "Podcast Listener",
    type: "podcast",
    description: "Complete 25 podcast episodes.",
    icon: "mic",
    active: true,
    threshold: 25,
  },
  {
    id: uid("bd"),
    name: "Research Explorer",
    type: "research",
    description: "View 15 research reports.",
    icon: "microscope",
    active: true,
    threshold: 15,
  },
  {
    id: uid("bd"),
    name: "Category Completion",
    type: "category",
    description: "Complete every item in a category.",
    icon: "check-circle",
    active: true,
    threshold: 1,
  },
  {
    id: uid("bd"),
    name: "Membership Anniversary",
    type: "anniversary",
    description: "Reach a membership anniversary.",
    icon: "award",
    active: true,
    threshold: 1,
  },
]

/* ----------------------------- API KEYS ----------------------------- */

const apiKeys: ApiKey[] = [
  {
    id: uid("ak"),
    name: "Mobile App (Production)",
    key: "gk_live_8f2c1a9b4d6e7f0c",
    scope: "content,user,feed",
    status: "active",
    lastUsed: daysAgo(0.1),
    createdAt: daysAgo(120),
    rateLimit: 1000,
  },
  {
    id: uid("ak"),
    name: "Analytics Pipeline",
    key: "gk_live_3b7e9c2a1d5f6b8e",
    scope: "analytics,read",
    status: "active",
    lastUsed: daysAgo(0.5),
    createdAt: daysAgo(80),
    rateLimit: 5000,
  },
  {
    id: uid("ak"),
    name: "Legacy Partner (Revoked)",
    key: "gk_live_0a1b2c3d4e5f6a7b",
    scope: "content",
    status: "revoked",
    lastUsed: daysAgo(40),
    createdAt: daysAgo(200),
    rateLimit: 200,
  },
]

/* ----------------------------- BACKUPS ----------------------------- */

const backups: BackupRecord[] = [
  {
    id: uid("bkp"),
    name: "gate-db-full-2025-08-25",
    type: "full",
    sizeMB: 1840,
    createdAt: daysAgo(1),
    status: "completed",
    verified: true,
  },
  {
    id: uid("bkp"),
    name: "gate-media-2025-08-25",
    type: "media",
    sizeMB: 6240,
    createdAt: daysAgo(1),
    status: "completed",
    verified: true,
  },
  {
    id: uid("bkp"),
    name: "gate-config-2025-08-24",
    type: "config",
    sizeMB: 12,
    createdAt: daysAgo(2),
    status: "completed",
    verified: true,
  },
  {
    id: uid("bkp"),
    name: "gate-db-full-2025-08-24",
    type: "full",
    sizeMB: 1810,
    createdAt: daysAgo(2),
    status: "completed",
    verified: false,
  },
]

/* ----------------------------- SYSTEM HEALTH ----------------------------- */

const systemHealth: SystemHealth[] = [
  { name: "API Gateway", status: "operational", latency: 42, detail: "All regions healthy" },
  { name: "Database", status: "operational", latency: 8, detail: "Primary + replica synced" },
  { name: "RSS Sync Worker", status: "operational", latency: 120, detail: "4 feeds processed" },
  { name: "Payment Provider", status: "degraded", latency: 380, detail: "Elevated latency on UPI" },
  { name: "Media CDN", status: "operational", latency: 22, detail: "Cache hit 98%" },
  { name: "Search Index", status: "operational", latency: 60, detail: "Index fresh" },
]

/* ----------------------------- ACTIVITY ----------------------------- */

const activity: { type: string; title: string; meta?: string; ts: number }[] = [
  { type: "publish", title: "Published book 'The Attention Republic'", meta: "IPN", ts: Date.now() - 0.1 * 86400000 },
  { type: "rss", title: "ISR RSS sync — 2 new episodes", meta: "ISR", ts: Date.now() - 0.05 * 86400000 },
  { type: "payment", title: "Payment received — 1 Year plan", meta: "GatePay", ts: Date.now() - 0.2 * 86400000 },
  { type: "edit", title: "Updated infographic 'Feed Mood'", meta: "IPN", ts: Date.now() - 0.3 * 86400000 },
  { type: "user", title: "New member registered: Priya Nair", meta: "Signup", ts: Date.now() - 0.4 * 86400000 },
  { type: "schedule", title: "Scheduled research 'Hadith Transmission Chains'", meta: "ISR", ts: Date.now() - 0.5 * 86400000 },
]

export const SEED = {
  books,
  research,
  infographics,
  podcasts,
  rss: rssFeeds,
  users,
  membershipPlans,
  payments,
  categories,
  tags,
  regions,
  topics,
  services,
  socialLinks,
  mediaAssets,
  notifications,
  auditLogs,
  badgeRules,
  apiKeys,
  backups,
  systemHealth,
  activity,
}

export function buildSeed() {
  return JSON.parse(JSON.stringify(SEED))
}

export const ADMIN_USER = {
  name: "Zayd Haji",
  email: "admin@gate.app",
  role: "Super Admin",
}
